apiVersion: workload.nephio.org/v1alpha1
kind: NFDeployment
metadata: # kpt-merge: example/cucp-example
  name: cucp-core
  namespace: oai-ran
  annotations:
    internal.kpt.dev/upstream-identifier: 'workload.nephio.org|NFDeployment|example|cucp-example'
spec:
  provider: cucp.openairinterface.org
  capacity:
  parametersRefs:
  - name: oai-cucp-config
    apiVersion: workload.nephio.org/v1alpha1
    kind: NFConfig
