apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata: # kpt-merge: example/smf-core-n4
  name: smf-core-n4
  namespace: example
  annotations:
    internal.kpt.dev/upstream-identifier: 'k8s.cni.cncf.io|NetworkAttachmentDefinition|example|smf-core-n4'
spec:
  config: '{"cniVersion":"0.3.1","name": "smf-core-n4","plugins":[{"type":"macvlan","capabilities":{"ips":true},"master":"ens19","mode":"bridge","ipam":{"type":"static"}}]}'
